import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css';

import Home from '../components/home/Home';


const HomePage = () => {
  return (
    <>
      <Head>
        <title>Next.JS - Sass</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />

    </>
  )
}


export default HomePage;